"""initial schema

Revision ID: 8a5fa6d64dc3
Revises:
Create Date: 2026-07-05 00:53:25.142294

"""

import sqlalchemy as sa
from alembic import op

revision = "8a5fa6d64dc3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chats",
        sa.Column("chat_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("chat_id"),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column(
            "last_seen",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "chat_settings",
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("welcome_enabled", sa.Boolean(), nullable=False),
        sa.Column("welcome_text", sa.Text(), nullable=True),
        sa.Column("delete_service_messages", sa.Boolean(), nullable=False),
        sa.Column("delete_welcome_after", sa.Integer(), nullable=True),
        sa.Column("captcha_enabled", sa.Boolean(), nullable=False),
        sa.Column("captcha_type", sa.String(length=20), nullable=False),
        sa.Column("captcha_timeout", sa.Integer(), nullable=False),
        sa.Column("captcha_fail_action", sa.String(length=20), nullable=False),
        sa.Column("warn_limit", sa.Integer(), nullable=False),
        sa.Column("warn_action", sa.String(length=20), nullable=False),
        sa.Column("warn_action_duration", sa.Integer(), nullable=True),
        sa.Column("filter_links", sa.Boolean(), nullable=False),
        sa.Column("filter_forwards", sa.Boolean(), nullable=False),
        sa.Column("filter_stopwords", sa.Boolean(), nullable=False),
        sa.Column("antispam_action", sa.String(length=20), nullable=False),
        sa.Column("antispam_exempt_admins", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.chat_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("chat_id"),
    )
    op.create_table(
        "mod_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("actor_id", sa.BigInteger(), nullable=False),
        sa.Column("target_id", sa.BigInteger(), nullable=True),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.chat_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_mod_log_chat_created", "mod_log", ["chat_id", "created_at"], unique=False
    )
    op.create_table(
        "stopwords",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("word", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.chat_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chat_id", "word", name="uq_stopwords_chat_word"),
    )
    op.create_table(
        "warns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("admin_id", sa.BigInteger(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.chat_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_warns_chat_user_active",
        "warns",
        ["chat_id", "user_id", "is_active"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_warns_chat_user_active", table_name="warns")
    op.drop_table("warns")
    op.drop_table("stopwords")
    op.drop_index("ix_mod_log_chat_created", table_name="mod_log")
    op.drop_table("mod_log")
    op.drop_table("chat_settings")
    op.drop_table("users")
    op.drop_table("chats")
    # ### end Alembic commands ###
